In [ ]:
import numpy as np

Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:

In [ ]:
a = np.array([1,2,3,4,5])

In [ ]:
#(a) Addition of 2 in all the element
print(a+2)

[3 4 5 6 7]


In [ ]:
#(b) Multiply 3 with all the elements
print(a*3)

[ 3  6  9 12 15]


In [ ]:
#(c) Divide every element by 2
print(a/2)

[0.5 1.  1.5 2.  2.5]


Q2.

In [ ]:
arr = np.array([1,2,3,6,4,5])

In [ ]:
#(a) Reverse the NumPy array
np.flip(arr)

array([5, 4, 6, 3, 2, 1])

In [ ]:
#(b)Find the most frequent value and their indice(s) in the following arrays:
#(i)
x = np.array([1,2,3,4,5,1,2,1,1,1])
frequency_x = np.bincount(x).argmax()
index= np.where(x == frequency_x)[0]
print(f"The most frequent value is {frequency_x} and its index is {index}")


The most frequent value is 1 and its index is [0 5 7 8 9]


In [ ]:
#(ii)
y = np.array([1,1,1,2,3,4,2,4,3,3])
frequency_y = np.bincount(y).argmax()
index_y = np.where(y==frequency_y)[0]
print(f"The most frequent value is {frequency_y} and its index is {index_y}")

The most frequent value is 1 and its index is [0 1 2]


Q3.

In [ ]:
arr1 = np.array([[10,20,30],[40,50,60],[70,80,90]])
#(a)
print(f"element at 1st row and 2nd col is {arr1[0][1]}")

element at 1st row and 2nd col is 20


In [ ]:
#(b)
print(f"element at 3rd row and 1st col is {arr1[2][0]}")

element at 3rd row and 1st col is 70


Q4.

In [ ]:
Rohin =np.linspace(10,100,25)
print(Rohin)
print(Rohin.ndim)
print(Rohin.shape)
print(Rohin.size)
print(Rohin.dtype)
print(Rohin.nbytes)

#transpose
reshape_transpose = Rohin.reshape(25,1)
print(reshape_transpose)
print(reshape_transpose.shape)

transpose_T = Rohin.T
print(transpose_T)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
1
(25,)
25
float64
200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
(25, 1)
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Q5.

In [ ]:
ucs420_Rohin = np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print(ucs420_Rohin)
ucs420_Rohin_mean = np.mean(ucs420_Rohin)
print(f"The mean of the array is {ucs420_Rohin_mean}")
ucs420_Rohin_median = np.median(ucs420_Rohin)
print(f"The median of the array is {ucs420_Rohin_median}")
ucs420_Rohin_max = np.max(ucs420_Rohin)
print(f"The maximum of the array is {ucs420_Rohin_max}")
ucs420_Rohin_min = np.min(ucs420_Rohin)
print(f"The minimum of the array is {ucs420_Rohin_min}")
ucs420_Rohin_unique = np.unique(ucs420_Rohin)
print(f"The unique values of the array are {ucs420_Rohin_unique}")
reshaped_ucs420_Rohin = np.reshape(ucs420_Rohin,(4,3))
print(f"The reshaped array is {reshaped_ucs420_Rohin}")
reshized_ucs420_Rohin = np.resize(ucs420_Rohin,(2,3))
print(f"The reshaped array is {reshized_ucs420_Rohin}")

[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
The mean of the array is 43.333333333333336
The median of the array is 37.5
The maximum of the array is 90
The minimum of the array is 10
The unique values of the array are [10 15 20 30 35 40 50 60 70 80 90]
The reshaped array is [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
The reshaped array is [[10 20 30]
 [40 50 60]]
