In [1]:
import numpy as np

Q1.

In [8]:
temperature = np.array([25,28,31,35,27,33,40])
#(a)
temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])
corrected = temperature + 2
print("Original temperatures:", temperature)
print("Corrected temperatures:", corrected)
#(b)
fahrenhite = ((9/5)*corrected)+ 32
print("Temperature in fahrenhite",fahrenhite)
#(c)
print("Readings greater than 32:",corrected[corrected>32])
#(d)
count = np.sum(corrected>32)
print("number of reading greater than 32:",count)
#(e)
print("""
Vectorization performs operations on the whole array at once, making the code faster and shorter.
Boolean indexing quickly filters values based on a condition without using a for loop.
""")


Original temperatures: [25 28 31 35 38 27 33 40]
Corrected temperatures: [27 30 33 37 40 29 35 42]
Temperature in fahrenhite [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
Readings greater than 32: [33 37 40 35 42]
number of reading greater than 32: 5

Vectorization performs operations on the whole array at once, making the code faster and shorter.
Boolean indexing quickly filters values based on a condition without using a for loop.



Q2.

In [3]:
steps = np.array([[5000,6200,7100],[8000,7500,9000],[4500,5100,4800],[9000,8500,9500]])
#(a)
total_steps = np.sum(steps)
print("Total:",total_steps)
#(b)
mean_steps = np.mean(steps)
print("Mean",mean_steps)
#(c)
max_steps = np.max(steps)
min_steps = np.min(steps)
print("max",max_steps)
print("min",min_steps)
#(d)
total_steps_axis0 = np.sum(steps,axis=0)
print("Daily totals:",total_steps_axis0)
#(e)
total_steps_axis1 = np.sum(steps,axis=1)
print("User totals:",total_steps_axis1)
#(f)
print("Maximum position:", np.unravel_index(np.argmax(steps), steps.shape))

Total: 84200
Mean 7016.666666666667
max 9500
min 4500
Daily totals: [26500 27300 30400]
User totals: [18300 24500 14400 27000]
Maximum position: (np.int64(3), np.int64(2))


Q3.

In [6]:
#(a)
original = np.array([1,2,3,4,5,6])
print("original:",original)
#(b)
subset = original[1:5]
print("subset:",subset)
#(c)
subset[0] = 999
print("original",original)
print("subset",subset)
#(d)
copied = original[1:5].copy()
copied[0] = 500
print("Original:", original)
print("Copied:", copied)
#(e)
arr = np.arange(1, 13).reshape(3, 4)
print("arr:\n", arr)
#(f)
print("First row:", arr[0])
print("Last row:", arr[-1])
print("Second column:", arr[:, 1])
print("Rows 1-2, Columns 2-3:\n", arr[0:2, 1:3])
#(g)
flat = arr.flatten()
rav = arr.ravel()
print("Flatten:", flat)
print("Ravel:", rav)
#(h)
rav[0] = 100
print("After modifying ravel:", arr)
#(i)
flat[1] = 200
print("After modifying flatten:", arr)
#(j)
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)
print("Data type:", arr.dtype)

original: [1 2 3 4 5 6]
subset: [2 3 4 5]
original [  1 999   3   4   5   6]
subset [999   3   4   5]
Original: [  1 999   3   4   5   6]
Copied: [500   3   4   5]
arr:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Rows 1-2, Columns 2-3:
 [[2 3]
 [6 7]]
Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12]
After modifying ravel: [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
After modifying flatten: [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Shape: (3, 4)
Dimensions: 2
Size: 12
Data type: int64


Q4.

In [9]:
y = np.array([40, 65, 30, 85])
X = np.array([[6, 70, 3],[5, 50, 6],[8, 80, 2],[4, 30, 8]])
#(a)
print("Shape:", X.shape)
print("Dimensions:", X.ndim)
#(b)
print("X.T:\n", X.T)
#(c)
prod = X.T @ X
print("X.T @ X:\n", prod)
#(d)
inverse = np.linalg.inv(prod)
print("Inverse:\n", inverse)
#(e)
beta = inverse @ X.T @ y
print("Coefficients:", beta)
#(f)
print("Sleep coefficient:", beta[0])
print("Activity coefficient:", beta[1])
print("Stress coefficient:", beta[2])
print("""
The coefficients show how each feature affects the assistance score.
A positive coefficient increases the score, while a negative coefficient decreases it.
""")
#(g)
new_user = np.array([5, 40, 7])
prediction = new_user @ beta
print("Predicted assistance score:", prediction)

Shape: (4, 3)
Dimensions: 2
X.T:
 [[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
X.T @ X:
 [[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]
Inverse:
 [[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]
Coefficients: [-0.15921454  0.14083853 10.06302242]
Sleep coefficient: -0.1592145415946895
Activity coefficient: 0.14083852991906243
Stress coefficient: 10.063022422714587

The coefficients show how each feature affects the assistance score.
A positive coefficient increases the score, while a negative coefficient decreases it.

Predicted assistance score: 75.27862544779117
